### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by cmoen** [LucidWorks/auto-phrase-tokenfilter#1]
If this software is meant to be open source, could you kindly add licensing information? Many thanks.

**Comment by cpilsworth** [comment]
Agreed, would be great if you could add a license

**Comment by mavarazy** [comment]
+1

**Comment by detnavillus** [comment]
License file added. Sorry for the delay - didn't get these notifications :(

**Comment by cmoen** [comment]
Thanks!
