### ISSUE TITLE
The source had not been built.

### ISSUE THREAD

**Issue by norvar** [LucidWorks/auto-phrase-tokenfilter#19]
Here is the error message.

[ivy:resolve] WARN:     ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] WARN:     ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve] WARN:     ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] WARN:     :: org.restlet.jee#org.restlet;2.1.1: not found
[ivy:resolve] WARN:     :: org.restlet.jee#org.restlet.ext.servlet;2.1.1: not found
[ivy:resolve] WARN:     ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]   report for com.lucidworks.demo#autophrase-tokenfilter;working@norvar default produced in C:\Users\xxxxx.ivy2\cache\com.lucidworks.demo-autophrase-tokenfilter-default.xml
[ivy:resolve]   report for com.lucidworks.demo#autophrase-tokenfilter;working@norvar compile produced in C:\Users\xxxxx.ivy2\cache\com.lucidworks.demo-autophrase-tokenfilter-compile.xml
[ivy:resolve]   report for com.lucidworks.demo#autophrase-tokenfilter;working@norvar test produced in C:\Users\xxxxx.ivy2\cache\com.lucidworks.demo-autophrase-tokenfilter-test.xml
[ivy:resolve]   resolve done (11201ms resolve - 118ms download)
[ivy:resolve]
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve]           module not found: org.restlet.jee#org.restlet;2.1.1
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.pom
[ivy:resolve]     -- artifact org.restlet.jee#org.restlet;2.1.1!org.restlet.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/org/restlet/jee/org.restlet/2.1.1/org.restlet-2.1.1.jar
[ivy:resolve]           module not found: org.restlet.jee#org.restlet.ext.servlet;2.1.1
[ivy:resolve]   ==== central: tried
[ivy:resolve]     http://repo1.maven.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.pom
[ivy:resolve]     -- artifact org.restlet.jee#org.restlet.ext.servlet;2.1.1!org.restlet.ext.servlet.jar:
[ivy:resolve]     http://repo1.maven.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.1.1/org.restlet.ext.servlet-2.1.1.jar
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: org.restlet.jee#org.restlet;2.1.1: not found
[ivy:resolve]           :: org.restlet.jee#org.restlet.ext.servlet;2.1.1: not found
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]
[ivy:resolve]
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED

**Comment by Pratik--Patel** [comment]
How was this issue fixed? I am getting the same error on running ant command.

**Comment by Pratik--Patel** [comment]
Never mind, found it. Solution is here.
https://github.com/lucidworks/auto-phrase-tokenfilter/issues/20
