### ISSUE TITLE
org.restlet.jee#org.restlet;2.1.1: not found

### ISSUE THREAD

**Issue by norvar** [LucidWorks/auto-phrase-tokenfilter#20]

**Comment by angelo337** [comment]
vim ivy/ivy-settings.xml

`<ivysettings>
    <settings defaultResolver="my-chain"/>
    <resolvers>
        <chain name="my-chain">
                <ibiblio name="restlet" m2compatible="true" root="http://maven.restlet.com"/>
                <ibiblio name="central" m2compatible="true"/>
        </chain>
    </resolvers>
    <modules>
        <module organization="org.restlet.jee" resolver="restlet"/>
        <module organization="restlet" resolver="restlet"/>
        <module organization="org.restlet" resolver="restlet"/>
    </modules>
</ivysettings>`
